#!/bin/bash

KEY_FILTER=cat
DOI_FILTER=cat
while getopts kd OPT; do
  case $OPT in
    k) KEY_FILTER='perl -pe "s/^[^ ]+ //"' ;;
    d) DOI_FILTER='perl -pe "s/ [^ ]*\n\$/\n/"' ;;
    *) exit 1 ;;
  esac
done
shift $((OPTIND - 1))

# fzf > peco > grep
if type fzf >/dev/null 2>&1 ; then
  PECO='fzf -i --ansi --multi --no-sort --layout=reverse-list --query="$*"'
elif type peco >/dev/null 2>&1; then
  PECO='peco  --layout=bottom-up --query="$*"'
else
  PECO='grep -i "$*"'
fi

# pbcopy > xsel > putclip
if type pbcopy >/dev/null 2>&1; then
  PBCOPY=pbcopy
elif type xsel >/dev/null 2>&1 ; then
  PBCOPY='xsel --input --clipboard'
elif type putclip >/dev/null 2>&1 ; then
  PBCOPY=putclip
else
  PBCOPY=true
fi

selection=$(gunzip -c $(dirname $(realpath $0))/dblp.txt.gz | eval $PECO)
# Don't clobber the clipboard when nothing was selected (e.g. aborted with ESC).
[ -n "$selection" ] || exit 0

printf '%s\n' "$selection" \
  | eval $KEY_FILTER \
  | eval $DOI_FILTER \
  | tee >(perl -pe 's/\e\[[;\d]*m//g' | eval $PBCOPY)
