#!/bin/bash

KEY_FILTER=cat
DOI_FILTER=cat
while getopts kd OPT; do
  case $OPT in
    k) KEY_FILTER='perl -pe "s/^\S+ //"' ;;
    d) DOI_FILTER='perl -pe "s/ http\S+$//"' ;;
    *) exit 1 ;;
  esac
done
shift $((OPTIND - 1))

# peco > fzf > grep
if type peco >/dev/null 2>&1; then
  PECO='peco --query="$*"'
elif type fzf >/dev/null 2>&1 ; then
  PECO='fzf --multi --query="$*"'
else
  PECO='grep -i "$*"'
fi

# pbcopy > xsel > putclip
if type pbcopy >/dev/null 2>&1; then
  PBCOPY=pbcopy
elif type xsel >/dev/null 2>&1 ; then
  PBCOPY='xsel --input --clipboard'
elif type putclip >/dev/null 2>&1 ; then
  PBCOPY=putclip
else
  PBCOPY=true
fi

gunzip -c $(dirname $(realpath $0))/dblp.txt.gz \
  | eval $PECO \
  | eval $KEY_FILTER \
  | eval $DOI_FILTER \
  | tee >(eval $PBCOPY)
